version: "3"

services:
  pgsqlQ:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: "pgsqlT"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: crud

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  api-logs:
  pg-data: